---
title: "Herring Framework 7"
author: Min-Yang Lee
date: "`r format(Sys.time(), '%B %d, %Y')`" 
output:
  pdf_document:
    keep_tex: TRUE
    fig_caption: Yes
  word_document: default
  html_document: 
   self_contained: TRUE
   toc: TRUE
   toc_float: TRUE
classoption: notitlepage
header-includes: 
  \AtBeginDocument{\let\maketitle\relax}
urlcolor: blue
editor_options:
  chunk_output_type: console
compact-title: FALSE
---


```{r global_options, include=FALSE}  
 desktopUse = ifelse(unname(Sys.info()["sysname"]) == "Windows", TRUE, FALSE)
# Different setups based on whether you are using Windows or Not-windows
  if (desktopUse) { # set the root path of the network, based on whether on desktop or server
    network_location = "//155.206.139.2"
    system("ipconfig", intern = TRUE)
  } else {
    network_location = "//net/"
  }

knitr::opts_chunk$set(echo=FALSE, warning = FALSE, error = FALSE, message = FALSE, comment = FALSE, cache = FALSE, progress = TRUE, verbose = FALSE, 
											dpi = 600)
options(tinytex.verbose = TRUE)
# options(knitr.table.format = "latex")

working_raster_folder<-file.path(network_location,"/work5/socialsci/Geret_Rasters/Data/individualrasters")

#These are inside the project, so they can be specified relatively if you want.
working_shapefile_folder<-file.path(network_location,"home2/mlee/READ-SSB-Lee-Raster_requests/input_data/Herring/Framework7")

#working_shapefile_folder<-"./input_data/Herring/Framework7/"

working_data_folder<-file.path(network_location,"home2/mlee/READ-SSB-Lee-Raster_requests/raw_data/Herring/Framework7")
#working_data_folder<-"./raw_data/Herring/Framework7/"

start_year<-2010
start_year<-2018
end_year<-2019
```	

```{r load_libraries, eval = T}  
#------------------------------- Remember to enter a selection (1 or 0) to sign into Google in this code chunk -------------------------------# 

# ### install offshoreWind package from Github if needed
if(!require(offshoreWind)) {
  if(!require(devtools)) {
    install.packages("devtools")
    require(devtools)}
  install_github("dcorvi/offshoreWind")
  require(offshoreWind)}

# PKG <- c("plyr", "foreign", "data.table", "dichromat", "RColorBrewer", "lattice", "scales",  "openxlsx", "sp", "rgdal",
#          "ggplot2", "dplyr", "tidyr", "stringr", "knitr", "lubridate", "devtools", "RODBC",  "googledrive", "googlesheets4") # remove plyr because of conflicts
PKG <- c("foreign", "data.table", "dichromat", "RColorBrewer", "lattice", "scales",  "openxlsx", "sp", "rgdal", "raster",
         "ggplot2", "dplyr", "tidyr", "stringr", "knitr", "lubridate", "devtools", "RODBC",  "googledrive", "googlesheets4")
for (p in PKG) {
  if(!require(p,character.only = TRUE)) {
    install.packages(p)
    require(p,character.only = TRUE)}
}
```




```{r first_step, eval=FALSE, include=FALSE, results='hide'}  
# This took 30 mins to an hour  on Mars to do 2 years.
getCallAreaEffort(raster_folder =working_raster_folder,
                  shapefile_f =working_shapefile_folder,
                  output_f =working_data_folder,
                  start = start_year,
                  end = end_year) 
```	

# This is the report for Herring Framework 7

# To do
1. Read through my herring raster request code, I've moved some of it to the "non_functional" folder.

1. Read through my confidentiality checker code.
 


# Here's another section

